# Generated by Django 5.2.7 on 2025-10-10 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('inventory', 'Отчет по остаткам'), ('movements', 'Отчет по движению товаров'), ('requests', 'Отчет по запросам ПВЗ'), ('statistics', 'Статистический отчет')], max_length=20, verbose_name='Тип отчета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата с')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата по')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='PDF файл')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='reports/excel/', verbose_name='Excel файл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('pickup_points', models.ManyToManyField(blank=True, to='warehouse.pickuppoint', verbose_name='ПВЗ')),
                ('sectors', models.ManyToManyField(blank=True, to='warehouse.sector', verbose_name='Секторы')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
