# Generated by Django 5.2.7 on 2025-10-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'ordering': ['name'], 'verbose_name': 'Пункт выдачи', 'verbose_name_plural': 'Пункты выдачи'},
        ),
        migrations.AlterModelOptions(
            name='productrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос товара', 'verbose_name_plural': 'Запросы товаров'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name'], 'verbose_name': 'Сектор', 'verbose_name_plural': 'Секторы'},
        ),
    ]
